spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ezshippingdb
    username: postgres
    password: Upc@2020

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

server:
<<<<<<< HEAD
  port: 8090
=======

  port: 8090  
  
>>>>>>> d38b4e050a281d33f32517a7129487fd4ed921f8
